version: "2"

services:
  app:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - rails-docker_bundle:/usr/local/bundle
    ports:
      - 3000:3000
    networks:
      - rails-api_network

volumes:
  rails-docker_bundle:

networks:
  rails-api_network: